#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 manage.py migrate --noinput
python3 manage.py shell << END
from django.contrib.auth import get_user_model
UserModel = get_user_model()
if UserModel.objects.filter(is_superuser=True).count() == 0:
    UserModel.objects.create_superuser('root', 'django-ledger@example.com', 'root')
END

>&2 true
python3 manage.py runserver 0:8000
